file(GLOB PB_PLATFORMS "${CMAKE_CURRENT_LIST_DIR}/*.cmake")

list(FILTER PB_PLATFORMS EXCLUDE REGEX "PB_Platforms.cmake") 

set(PB-CONFIG_PLATFORM "SELECT PLATFORM" CACHE STRING "PB Platform")
set_property(CACHE PB-CONFIG_PLATFORM PROPERTY STRINGS ${PB_PLATFORMS})

if(PB-CONFIG_PLATFORM STREQUAL "SELECT PLATFORM")

	foreach(platform ${PB_PLATFORMS})
		string(APPEND VALUES "-> ${platform}\n")
	endforeach()
	
	message(FATAL_ERROR "Set PB-CONFIG_PLATFORM: \n${VALUES}")

else()
	set(PB_PLATFORM_DIR ${CMAKE_CURRENT_LIST_DIR})
	SEPARATE_ARGUMENTS(PB-CONFIG_PLATFORM)
	include(${PB-CONFIG_PLATFORM})
endif()